### ISSUE TITLE
point jumps after barfing

### ISSUE THREAD

**Issue by ssfrr** [luxbock/evil-cleverparens#105]
if I start from this, (where `^` is point)
```elisp
(test foo bar) (baz)
^
```

and press `>` to barf, I end up with

```
test (foo bar) (baz)
               ^
```

So the resulting code is what I expect, but point has jumped to the beginning of the next sexp, rather than staying on the same paren.

Is this intended? My mental model of `<` and `>` for slurping and barfing is that you're basically moving the parentheses around, but I'm not sure if that's the right way to think about it.

**Comment by ssfrr** [comment]
seems like this is maybe related to [this issue](https://github.com/emacs-evil/evil-cleverparens/issues/21#issuecomment-145247309), but it looks like that was resolved.

**Comment by tomdl89** [comment]
Thanks for the bug report @ssfrr - I can replicate it, after I updated smartparens. This behaviour was brought in by [this](https://github.com/Fuco1/smartparens/commit/219da7202c6c184ac06033489899bfc391ddd64e) commit. The quick fix is to add `(setq sp-barf-move-point-with-delimiter nil)` to your config, but I'll take a look to see if it's worth evil-cleverparens binding this value to `nil` when barfing, if it's never useful to us.

**Comment by tomdl89** [comment]
Yeah, I'm pretty sure it's never useful in the specific case of barfing from the opening delimiter, so I've changed `evil-cp->` to force `sp-barf-move-point-with-delimiter` to be `nil`. So this should fix your problem @ssfrr . Let me know if you observe otherwise.

**Comment by zane** [comment]
I can reproduce this, but when barfing from the closing parenthesis. With `sp-barf-move-point-with-delimiter` set to `t` press `<` and the cursor jumps to the previous closing parenthesis. 

**Before**

```
()
(0 1 2 3)
        ^
```

**After**

```
()
 ^
(0 1 2) 3
```

Note that this only happens if there _is_ a previous closing parenthesis:

```
(0 1 2 3)
        ^
```

**After**

```
(0 1 2) 3
      ^
```

**Comment by tomdl89** [comment]
@zane I was able to reproduce and fix. This is now merged. Please let me know if you observe otherwise.
