### ISSUE TITLE
Using a form that contains an escaped bracket character breaks

### ISSUE THREAD

**Issue by elken** [luxbock/evil-cleverparens#109]
When editing clojure that has a form containing `\(`, it's incorrectly marked as a delimiter and breaks the whole form.

I have a [preliminary fix](https://github.com/emacs-evil/evil-cleverparens/compare/master...elken:evil-cleverparens:fix/delete-escaped-parens) but it doesn't seem to be quite right.

Below is the code I've been using to verify

```clojure
(defn no-brace []
  (println "hi"))

(defn brace []
  (println \())
```

I can repro with a vanilla Emacs with just `clojure-mode`, `evil` and `evil-cleverparens` installed and enabled. I imagine this will also break with `?(` keycodes in emacs lisp.

**Comment by tomdl89** [comment]
Thanks @elken ! Can you enumerate what problems "breaks the whole form" means, just so I'm sure I'm not missing anything? When I do `dd` on the last last line of break, it throws an error, which is caused by evil-cp incorrectly assuming `sp-get-enclosing-sexp` will return a struct with `:beg` and `:end` props. Although we may be able to work around this in evil-cp, my initial understanding is this is an upstream bug in smartparens. Let me know if you think otherwise 🙏

**Comment by tomdl89** [comment]
I've fixed the deletion problems here: https://github.com/tomdl89/evil-cleverparens/tree/fix/delete-escaped-parens
lmk if there's more I've missed

**Comment by elken** [comment]
Yes just to clarify then all commands no longer function correctly, I can't yank past the entire form (if you `yG` in the buffer containing that code you only get the first function), deletion also doesn't work as you identified.

> Although we may be able to work around this in evil-cp, my initial understanding is this is an upstream bug in smartparens

Hmm, you could be right. I'll see if that branch resolves it for now at least


EDIT: This looks to be resolved upstream AFAICT with https://github.com/Fuco1/smartparens/issues/684

That branch also doesn't seem to work quite right, the form deletes but the escaped paren is left on its own


https://github.com/emacs-evil/evil-cleverparens/assets/2872862/6bae5d1a-0ae3-44e1-a685-b85abcbbb643

**Comment by tomdl89** [comment]
I'm not sure I can replicate. What keypresses are you doing in the video?

**Comment by elken** [comment]
> I'm not sure I can replicate. What keypresses are you doing in the video?

`dG`, `dd`, `yG`

**Comment by tomdl89** [comment]
Hmm can you double check you've pulled/loaded my branch properly? Those keypresses all work for me. Maybe easier to pair some time next week if easier.

**Comment by elken** [comment]
Yeah I definitely am, I've got this defined
![image](https://github.com/emacs-evil/evil-cleverparens/assets/2872862/ee87da69-dbdb-42fd-bd61-939911c94854)

I'll try it in vanilla

**Comment by tomdl89** [comment]
One nice way to double check is to see if you have `evil-cp--looking-at-escape-p` defined too (note `escape` rather than `escaped`), as I added that too.

**Comment by elken** [comment]
> One nice way to double check is to see if you have `evil-cp--looking-at-escape-p` defined too (note `escape` rather than `escaped`), as I added that too.

Both there yeah

**Comment by tomdl89** [comment]
Huh weird. If you can replicate in vanilla, let's take a look next week :)

**Comment by elken** [comment]
Seems I can't so that seems to be a doom issue.

Will just revert the branch to double check it still breaks in vanilla and then I consider this closed

EDIT: Yep that works for vanilla, so I consider this resolved :) 


https://github.com/emacs-evil/evil-cleverparens/assets/2872862/ea895130-afce-4514-886e-fa0cb6919cfc

**Comment by tomdl89** [comment]
Interesting! Lmk if you find the doom-side cause. Might be something we can address here. Also I've just thought, although deleting is fixed, yanking probably isn't, so I'll check and fix that before merging. Thanks!

**Comment by elken** [comment]
> Interesting! Lmk if you find the doom-side cause. Might be something we can address here. Also I've just thought, although deleting is fixed, yanking probably isn't, so I'll check and fix that before merging. Thanks!

Yanking seems to work fine in the clip, even line yanking works

**Comment by tomdl89** [comment]
Oh cool, that's a relief

**Comment by elken** [comment]
Wouldn't hurt to add tests for it though :)

**Comment by elken** [comment]
And in terms of Doom, I've uncommented the entirety of the `sp` config and it works as expected, so it seems there's a potential upstream bug here or just some misconfiguration

Thanks!

EDIT: Confirmed this to be setting `sp-navigate-skip-match` to `nil` for performance reasons [here](https://github.com/doomemacs/doomemacs/blob/24601b300e87e909340524476713dcaaa5d095cd/modules/config/default/config.el#L97)

**Comment by tomdl89** [comment]
Ah good find! I'll have a play with this set to nil to see if there's anything we can do, while allowing doom users to keep their performance gains.

**Comment by tomdl89** [comment]
Note: this was fixed for when `sp-navigate-skip-match` includes the current mode, here: https://github.com/emacs-evil/evil-cleverparens/commit/134fe3396f975fb1ad261f52cd113f42ac1da4fc. Fixing for when it doesn't include the current mode is not planned, but a concise PR would be welcomed.
