### ISSUE TITLE
Backspacing over an opening paren deletes only that paren

### ISSUE THREAD

**Issue by mtwomey** [luxbock/evil-cleverparens#112]
When I am in edit mode and I open a pair of parenthesis, I get the closing paren (as expected). However, if I immediately backspace over the opening paren, the closing paren is left behind.

I see that backspace is mapped to `evil-delete-backward-char-and-join` in this case. Does cleverparens account for this, or maybe I have something setup wrong?

**Comment by tomdl89** [comment]
As replied on Clojurians slack, I don't think this is a cleverparens issue. Feel free to reopen if you discover otherwise.
