### ISSUE TITLE
dd not deleting a line

### ISSUE THREAD

**Issue by steeni** [luxbock/evil-cleverparens#115]
When in elisp mode I press dd to delete whole line safely, dd doesn't delete anything. Not even for empty lines. I expected dd to delete the whole line safely.

When I use dj to remove 2 lines it does work. I had same behavior in the past with lispyville so I'm thinking it could be something in my own configs but didn't find anything that interferes. Is it a bug, a design choice or a misconfiguration on my side?

C-h k d shows evil-cp-delete in lisp modes so it should be using the correct thing. I'm using emacs built from the master branch (30.0.50).

**Comment by tomdl89** [comment]
Hey @steeni that sounds a bit strange. It's not a design choice. Could be a bug, but `dd` is so commonly used, I'd be surprised if it is. Most likely configuration related on your side. One thing that may help me offer advice is if you do `M-x debug-on-entry` and choose `evil-cp-delete` and paste the backtrace here after doing `dd`.

**Comment by steeni** [comment]
Thanks for helping. I tried to get backtrace and results are weird. I forgot to mention I was editing elisp in src block in the org mode with recursive edit C-'. There debug-on-entry does not trigger with dd. It does trigger with dj. Here is the trace with dj:

```
Debugger entered--entering a function:
* evil-cp-delete(164 166 line nil nil)
  funcall-interactively(evil-cp-delete 164 166 line nil nil)
  command-execute(evil-cp-delete)
```

I also tried diagnosing with a normal el file. There the debugger advice does trigger with dd and when debugger is on, the functionality also works correctly. However, when I cancel-debug-on-entry and try again it does not work. Somehow the debugger advice affects it so that it works. Here is the trace with dd from el file.

```
Debugger entered--entering a function:
* evil-cp-delete(82 83 line nil nil)
  funcall-interactively(evil-cp-delete 82 83 line nil nil)
  command-execute(evil-cp-delete)
```

I'm pretty sure there's something in my config that causes this (or the bleeding edge emacs version). Probably should create simplified bare minimum configuration and see if it still occurs. If I am able to narrow it down I will report back.

**Comment by tomdl89** [comment]
Yeah, something strange is going on, most likely with your config. I can't replicate in an elisp org mode source block, and
> There debug-on-entry does not trigger with dd.

makes me think something's up with your config too. Let me know where you get to creating a simplified bare minimum repro.

**Comment by steeni** [comment]
I was able to narrow it down and it has nothing to do with evil-cleverparens. Disabling doom-modeline fixed it. I don't know exactly what causes it but could somehow be related with showing evil-state in modeline. Anyway, you can close this.
