### ISSUE TITLE
Disabling additional structural movement bindings

### ISSUE THREAD

**Issue by sooheon** [luxbock/evil-cleverparens#13]
I have tried `(setq evil-cleverparens-use-additional-bindings nil)`, as well as custom-set-variables, and both do not seem to take effect. Can anybody reproduce this?

**Comment by luxbock** [comment]
Because this is the first time I'm writing a proper minor-mode in Emacs, I'm a bit green on how to properly set-up the keybindings, sorry about that. I think I know why it's not working right now but I'll have to take a better look at it tomorrow.

**Comment by luxbock** [comment]
I think this works now, or at least when I tested it myself the mode would check for the settings before enabling the related keybindings. I also made it so that you can change the setting and then call the `evil-cp-set-X` function to enable/disable the keybindings in question.

**Comment by sooheon** [comment]
Thanks. It does work, but I realized what I wanted to disable was not additional bindings, but `evil-cp-additional-movement-keys`. Having a look through the source, I see that you have it go through a progn and enable various bindings, but you only have a conditional for additional (M- prefixed) bindings. What do you think about adding conditionals and relevant defcustoms for each of those sets of bindings, to allow for more fine grained choice? Or you could even do something like lispy does with `lispy-set-key-theme`.

**Comment by luxbock** [comment]
Check out `evil-cp-set-additional-movement-keys`,  it sould work just the
same but I didn't actually try it myself yet.
