### ISSUE TITLE
Separate Text Objects From evil-clever-parens-mode

### ISSUE THREAD

**Issue by noctuid** [luxbock/evil-cleverparens#15]
Since the comment and form text objects work for more than just lisp modes (modes where the user would want `evil-cleverparens-mode` enabled), it might make sense to pull `(evil-cp--enable-text-objects)` out of `evil-clever-parens-mode` and add autoloads for each text object individually (which would also mean that the users could choose a different key for binding them if they wanted). For example, one might want to use the comment text object before ever entering some lisp mode, and currently, the text objects will not be defined/bound until the user has started the `evil-cleverparens-mode` once.

**Comment by luxbock** [comment]
Yeah good point, I'll look into this once I get done with working on improving the dragging behavior and a few other issues that have popped up.

**Comment by luxbock** [comment]
I separated them out to their own file so that the use case is solved by requiring `'evil-cleverparens-text-objects`.

**Comment by noctuid** [comment]
@luxbock The autoload cookies don't recognize `evil-define-text-object`, so they pull the entire sexp into the autoloads file (instead of creating an `(autoload...)` like they would above a defun) when built with package.el. I think you have to write out the full autoload with the cookie:

```
;;;###autoload (autoload 'evil-cp-a-form "evil-cleverparens-text-objects" nil t)
```
