### ISSUE TITLE
Yanking multiple lines

### ISSUE THREAD

**Issue by justbur** [luxbock/evil-cleverparens#28]
Ran into this today. Example

``` elisp
(when ready
  (let (a b)
    (setq a 1
          b 2)
    (command a b)))
```

use `V` to select the last three lines and `y`. Then moving somewhere else, `p` gives

``` elisp
(setq a 1
      b 2)
(command a b)))
```

notice the extra parens. The extra parens are not there if you just `yy` on the last line

**Comment by luxbock** [comment]
Yeah it appears that `y` in visual state is bound to `evil-yank` instead of `evil-cp-yank`, so it should be an easy fix. Calling `evil-cp-yank` via `M-x` works fine.

**Comment by justbur** [comment]
Ok cool. Sorry that should have been obvious if I checked.

**Comment by justbur** [comment]
This seems to be fixed
