### ISSUE TITLE
handling comments

### ISSUE THREAD

**Issue by justbur** [luxbock/evil-cleverparens#32]
Hi again,

I was wondering if there was a way to intelligently deal with comments. Here's an example

``` elisp
(let (a)
  ;; a is ...
  (setq a 1))
```

Try `dd` on the last line. The closing paren moves into the comment and now we have a problem and need a manual fix. Is it possible to jump the comment or put the closing paren before the comment? Something that would keep the expression valid.

**Comment by justbur** [comment]
I would be fine with this result too

``` elisp
(let (a)
  ;; a is ...
  )
```

**Comment by luxbock** [comment]
Turned out to be a rather easy fix :)

**Comment by justbur** [comment]
Thanks! I thought it might be
