### ISSUE TITLE
support for clojure?

### ISSUE THREAD

**Issue by drorbemet** [luxbock/evil-cleverparens#33]
Does evil-cleverparens intend to support clojure specific edge cases?

**Comment by luxbock** [comment]
Clojure and Emacs Lisp are the two languages I mostly use so definitely. What are the edge cases you have in mind?

**Comment by drorbemet** [comment]
Oh, that sounds great, thanks. Right now I don't have a specific case that does not work. But I am glad to know that it would be considered a priority if one occurs.

**Comment by luxbock** [comment]
`evil-cleverparens` is built on top of `smartparens`, so if you configure `smartparenes` to work with Clojure then most things should just work. See `sp-sexp-prefix` in particular.
