### ISSUE TITLE
Form text-object bug

### ISSUE THREAD

**Issue by uzhne** [luxbock/evil-cleverparens#35]
``` elisp
(f ;; (
 'x)
```

Calling `evil-cp-a-form` with the point at `f` results in

> Search failed. This means there is unmatched expression somewhere or we are at the beginning/end of file.
> evil-cp-a-form: Wrong type argument: number-or-marker-p, nil

**Comment by luxbock** [comment]
Seems to be a problem with `sp-get-enclosing-sexp` and deeper down at `sp-get-paired-expression`. I've filed an issue with smartparens:

Fuco1/smartparens#556

**Comment by uzhne** [comment]
Alright, thanks! I should've looked more carefully into it.

**Comment by luxbock** [comment]
This should be fixed now if you use the latest version of smartparens.
