### ISSUE TITLE
whitespace after daf and dab

### ISSUE THREAD

**Issue by justbur** [luxbock/evil-cleverparens#36]
Hi, This is a minor annoyance for me, but maybe there's something you can do about it. Here's an example, where I'm using `.` to represent spaces

``` elisp
;;.A.sentence.in.a.comment
(progn.(a).(sequence).(of).(commands))
```

If I `daw` on "sentence", I get

``` elisp
;;.A.in.a.comment
(progn.(a).(sequence).(of).(commands))
```

but `daf` on `sequence` then gives

``` elisp
;;.A.in.a.comment
(progn.(a)..(of).(commands))
```

Notice when I delete "sentence" it also deletes one space, but I'm left with two spaces between `(a)` and `(of)`, which I typically then have to fix right away.

Maybe this is too complicated to fix, but if it's not, I'd appreciate it if the behavior with regards to whitespace leftover was consistent. 

By the way I've been using this package for a while now, and it really makes editing lisp much more pleasant, so thank you.

**Comment by luxbock** [comment]
Yeah I agree your suggested behavior would be desirable, but at first glance I couldn't figure out how to make it work like that. The special handling of whitespace with `dd` works by attaching a `yank-handler` that takes care of it, but as far as I can tell that's not possible with text objects. I'll leave this open for now and see if I can come up with another idea.

You are welcome! I'm glad other people are enjoying it as I can't imagine not using it myself anymore :)

**Comment by justbur** [comment]
I'm not worried about it
