### ISSUE TITLE
Disable conflicting key-bindings M-w and M-[

### ISSUE THREAD

**Issue by skovuri41** [luxbock/evil-cleverparens#39]
Hi,

I am looking for help in how to disable certain key bindings in evil-cleverparens mode eg: M-w, M-[ as these casuing conflicts with certain other modes I use. 

It can be categorized as not an issue but any help with extra documentation will certainly help.

**Comment by skovuri41** [comment]
let me answer my question , so far i have this, kind of working but 'key x' is not working:

`
(use-package evil-cleverparens
      :diminish evil-cleverparens-mode
      :init
      (progn
        (defun set-cleverparens-key-bindings ()
          (progn  (evil-define-key 'normal evil-cleverparens-mode-map (kbd "M-w") nil)
                  (evil-define-key 'normal evil-cleverparens-mode-map (kbd "M-[") nil)
                  (setq evil-move-beyond-eol nil)
                     ))
        (add-hook 'evil-cleverparens-enabled-hook 'set-cleverparens-key-bindings)
        (add-hook 'emacs-lisp-mode-hook 'evil-cleverparens-mode)
        (add-hook 'clojure-mode-hook 'evil-cleverparens-mode)
        )
      )
`

**Comment by luxbock** [comment]
I think if you first remove the unwanted keys from `evil-cp-additional-bindings` and then call `evil-cp-set-additional-bindings` afterwards then that alone should work.

**Comment by skovuri41** [comment]
thanks I will try it.
