### ISSUE TITLE
evil-cp-delete-line corner case

### ISSUE THREAD

**Issue by sooheon** [luxbock/evil-cleverparens#42]
Given:

```
(spacemacs|define-transient-state sooheon-paste
  "\n[%
[_M-n_/_M-p_] cycles through yanked text, [_p_/_P_] pastes the same text above or
below. Anything."
  :bindings
  ("M-n" evil-paste-pop))
```

With cursor anywhere on line 4, `D` will return something like this:

```
(spacemacs|define-transient-state sooheon-paste
  "\n[%
[_M-n_/_M-p_] cycles through yanked text, [_p_/_P_] pastes the same text above or
M-n" evil-paste-pop))
```

with unbalanced parens. The snippet above is not valid elisp (I was looking for minimum reproducible fragment), but syntactically it's correct. The problem is that instead of deleting only to the end of the current string, it joins all the way to the start of the next string, deleting everything inbetween. I think the problem has something to with the weird characters in the string, as deleting the middle line of the multiline string makes this unreproducible.

**Comment by luxbock** [comment]
Yeah I can reproduce the issue, but unfortunately I'm really busy right now, so trying to find a fix may take some time.

**Comment by tomdl89** [comment]
@sooheon I'm going through old issues and looking to fix them or close them. I can't reproduce this (even checking out the latest commit as of Mar 12, 2016). So will probably close, unless you can give updated / clarified repro steps?
