### ISSUE TITLE
Please don't rebind keys every time the mode is enabled

### ISSUE THREAD

**Issue by justbur** [luxbock/evil-cleverparens#43]
Most of the key bindings go into the mode map, which only needs to be populated once. Binding the keys in the mode toggle function means that to change them I either need to manipulate the variables holding the bindings or rebind in a hook, both of which seem unnecessarily complicated. If you just define the keys in the map once, I can just change the binding in the map directly.

**Comment by luxbock** [comment]
Yeah good point. I am very busy lately so a PR for this would be nice, or I can take a look at it in a few weeks.

**Comment by justbur** [comment]
No rush. I figured out my particular problem. I was just mentioning it as a
minor annoyance.
