### ISSUE TITLE
How to move backwards and downwards into previous sexp?

### ISSUE THREAD

**Issue by bpstahlman** [luxbock/evil-cleverparens#57]
I looked through the documentation and didn't see a way to move backwards and downwards into a sexp: something like paredit-backward-down (C-M-p). Actually, I don't see a command for moving forward and down into a list either: something like paredit-forward-down. I'm thinking this functionality must exist, so perhaps I'm just overlooking it...

**Comment by luxbock** [comment]
While not exactly the same, `evil-cp-next-closing` and `evil-cp-previous-closing` are the closest things to what you are looking for (bound to `{` and `}`).

**Comment by bpstahlman** [comment]
Ok. Thanks.
