### ISSUE TITLE
cw swallows space after word

### ISSUE THREAD

**Issue by aaronjensen** [luxbock/evil-cleverparens#59]
In regular evil and vim, `cw` in this case:

```
foo |bar baz
```

Will drop you into insert in:

```
foo | baz
```

In evil-cp, it seems to be:

```
foo |baz
```

which is unexpected. Is there a way around this? I don't plan to change my muscle memory to use `ce` :/

**Comment by chipset1** [comment]
You can unbind evil-cp's binding to "c" which should revert it to use evils. 

`(evil-define-key 'normal evil-cleverparens-mode-map
    "c" nil)`

but you could end up with unbalanced parens since you could change a single opening or closing paren.

**Comment by jgkamat** [comment]
this is the same issue as https://github.com/expez/evil-smartparens/issues/20.

This is really a wierd issue, because it's triggered even if you copy the def for `evil-change` and bind to your definition. Evil must be hard coding some exception for `evil-change` somehow.

I'm going to see if I can track it down on the evil side.

**Comment by aaronjensen** [comment]
Yes, it's also a similar issue to https://github.com/emacs-evil/evil-surround/issues/117

You're right that it is hardcoded: https://github.com/emacs-evil/evil/blob/dc936936666595afdbdbb4cc44c1f82e74c6802c/evil-commands.el#L309-L311

**Comment by jgkamat** [comment]
I'm pretty annoyed at this issue (I've been struggling with it for many months now) so I'm going to create an issue in evil and see if we can get a list of modes (so evil-cleverparens and similar can add their evil-change functions to it). Hopefully I'll come back with a PR to here to add `evil-cp-change` to that list.

**Comment by aaronjensen** [comment]
Sounds good. I think that [this](https://github.com/emacs-evil/evil-surround/issues/117#issuecomment-317364008) is the most reasonable solution I've heard so far, so a list of commands rather than a list of modes.
