### ISSUE TITLE
Change modifier key for evil-cp-additional-bindings?

### ISSUE THREAD

**Issue by eggsyntax** [luxbock/evil-cleverparens#60]
The documentation for evil-cp-additional-bindings says: "Alist containing additional functionality for evil-cleverparens via a modifier key (using the meta-key by default)." Is it possible to change the modifier key to (say) Alt?

Thanks!

**Comment by luxbock** [comment]
As it is this is not really possible, but I would accept a pull request that allows one to customize the modifier key. Sorry about that, I know the design for the keybindings was not very optimal.
