### ISSUE TITLE
Use '[[' and ']]' instead of bare '[' and ']'

### ISSUE THREAD

**Issue by futuro** [luxbock/evil-cleverparens#61]
Evil-unimpared uses `[-<SPC>` and `]-<SPC>` to add spaces above and below the current line, but when you add evil-cleverparens-mode to the clojure-mode hook it clobbers the whole prefix space with `evil-cp-previous-opening` and `evil-cp-next-closing`.

If the mappings were to use `[[` and `]]` instead then the `[` and `]` prefix spaces would be left open for other packages to utilize as well.

**Comment by luxbock** [comment]
I am so used to the way things work as it is, and I use `[` and `]` a lot, that I won't change this for the default case. I think it should be possible to customize the keys for each user if they conflict with other packages.
