### ISSUE TITLE
HELP 

### ISSUE THREAD

**Issue by tdblocks** [luxbock/evil-cleverparens#68]
After downloading emacs following http://eschulte.github.io/emacs24-starter-kit/#emacs-lisp-package-archive, I now want to enable Melpa.  

The below is what I typed into an org document under the directory emacs.d : 
#+BEGIN_SRC emacs-lisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)
#+END_SRC

upon typing C-c C-c, I get the response "Wrong type argument: listp, "http://melpa.org/packages/"

What am I doing wrong??? I'd greatly appreciate any help offered.

**Comment by tdblocks** [comment]
After restarting Emacs, I am getting this new message when repeating the above steps: 

"Symbol's value as variable is void: package-archives"

**Comment by vyp** [comment]
You may want to try opening an issue at https://github.com/melpa/melpa instead.

https://github.com/melpa/melpa#usage says how to enable melpa. Make a file named `init.el` under `.emacs.d` directory, and put that code in it.
