### ISSUE TITLE
Text objects does not work

### ISSUE THREAD

**Issue by achikin** [luxbock/evil-cleverparens#72]
As far as I understand - text objects should allow me operate on those objects while using yank/delete/etc operations. But `df` does not delete a form and non of the other such commands work. Am I missing something?

**Comment by jgkamat** [comment]
Works fine here, have you done:

`(require 'evil-cleverparens-text-objects)`?

**Comment by achikin** [comment]
It is already included into `evil-cleverparens.el`. I'm sorry, I should have learned my Vim lessons better. `f` for function and `d` for defun are only availabe in inner and outer objects e.g. `df` does not work but `daf` and `dif` do what expected. My bad.
