### ISSUE TITLE
Make evil-cleverparens-swap-move-by-word-and-symbol have effect in operator mode

### ISSUE THREAD

**Issue by kommen** [luxbock/evil-cleverparens#76]
Currently setting `evil-cleverparens-swap-move-by-word-and-symbol` only swaps the keys in normal mode. For the sake of consistency, I think it would make sense to swap them as well in operator mode.

Would this be desirable?

**Comment by tomdl89** [comment]
Fixed here: https://github.com/emacs-evil/evil-cleverparens/commit/63a180238b33f0a7f2c8ae0733069e704bff85da
