### ISSUE TITLE
`evil-cp-*-symbol-*` does not skip `#()`

### ISSUE THREAD

**Issue by achikin** [luxbock/evil-cleverparens#80]
Cleverparens symbol movement treats `#()` as a symbol
Example:
Consider the following clojure code, I'm pressing `w` several times
![image](https://user-images.githubusercontent.com/611419/98468335-18adb300-21eb-11eb-9a33-f7ad6bbded53.png)
![image](https://user-images.githubusercontent.com/611419/98468347-1fd4c100-21eb-11eb-9b67-35be46f88b8e.png)
![image](https://user-images.githubusercontent.com/611419/98468356-282cfc00-21eb-11eb-8f87-2fd1d4e75d9d.png)
![image](https://user-images.githubusercontent.com/611419/98468367-2feca080-21eb-11eb-8e14-5fba6cc71bdb.png)
As far as I understand in this case cursor should not stop on `#`

**Comment by tomdl89** [comment]
@achikin although >2yrs late, this should now be fixed in master. Please let me know if you observe otherwise.
