### ISSUE TITLE
Transfer to emacs-evil

### ISSUE THREAD

**Issue by tomdl89** [luxbock/evil-cleverparens#83]
Hi @luxbock - it appears this repo may no longer be maintained, so I'm interested to know if you would consider transferring this repo to https://github.com/emacs-evil ? I know a few people (myself included) in the Clojure community point to forks which have fixed various bugs or added features, and I assume that is because they haven't had much luck getting them merged here. I may be wrong, so please correct me if so! I'm a member of emacs-evil and the maintainer of evil, so I can help facilitate the transfer and redirect MELPA etc if you're happy to do so. Thanks :)

**Comment by tomdl89** [comment]
@luxbock any update on this?

**Comment by luxbock** [comment]
Hey, sorry for being so slow to reply.

Yes I would be happy to transfer the project. How should I go about doing this?

**Comment by tomdl89** [comment]
No problem at all. To transfer, click on the `Settings` tab at the top of this repo and scroll to the bottom. In the `Danger Zone` there is a `Transfer ownership` option. Click `Transfer`, type in `emacs-evil` and the other bits. Let me know if you have any problems. Thanks!

**Comment by luxbock** [comment]
I am getting an error saying:

> You don’t have the permission to create public repositories on emacs-evil  

When I try to transfer.

**Comment by tomdl89** [comment]
Oh, I'll make you a member of evil, one sec...

**Comment by tomdl89** [comment]
Invite sent

**Comment by luxbock** [comment]
Hmm I am still getting the same error. I'll give it a moment and try again.

**Comment by tomdl89** [comment]
Looks successful to me. Thanks for transferring!
