### ISSUE TITLE
x/X splices outer sexp rather than one on cursor

### ISSUE THREAD

**Issue by bo-tato** [luxbock/evil-cleverparens#96]
```
    x on opening ( deletes the quotes
             v
#"(?<=^|\n| )()7[a-zA-Z0-9]{25,34}( |\n|$)"
              ^
            x on closing ) deletes the () as expected
```
you would expect x on the opening paren to delete the parens. This is just latest example I found but it was happening to me fairly regularly that x spliced the outer sexp rather than the one under the cursor, enough that I unbound x from `evil-cp-delete-char-or-splice` and just use splice when i want to delete matching parens. other than that minor issue I'm quite happy with the plugin, thanks for making it!

**Comment by tomdl89** [comment]
@bo-tato thanks for the bug report! I'll take a look soon. Is this a recent regression, or something you've noticed for a while?

**Comment by bo-tato** [comment]
I wouldn't know, I just started using emacs a couple weeks ago. thanks for looking into it

**Comment by tomdl89** [comment]
Ah, well welcome! I can replicate this, so should have a fix soon.

**Comment by tomdl89** [comment]
A note for MRE:
```
"()"
```
On opening paren, `x` splices the quotes, on closing paren, it splices the parens.

**Comment by bo-tato** [comment]
ah yea, the last occurrence and only one I noted down was that ugly regex, but thinking the times it happened before I think it was always involving quotes also

**Comment by tomdl89** [comment]
@bo-tato that should now be fixed in master. Please let me know if you observe otherwise

**Comment by bo-tato** [comment]
great, fix is working for me!
